# Generated by Django 5.1.7 on 2025-03-29 01:12

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_message_1', django_ckeditor_5.fields.CKEditor5Field()),
                ('head_message_1_paragraph_1', django_ckeditor_5.fields.CKEditor5Field()),
                ('head_message_1_message_1', django_ckeditor_5.fields.CKEditor5Field()),
                ('head_message_1_message_2', django_ckeditor_5.fields.CKEditor5Field()),
                ('head_message_1_message_3', django_ckeditor_5.fields.CKEditor5Field()),
                ('head_message_1_message_4', django_ckeditor_5.fields.CKEditor5Field()),
                ('head_message_1_paragraph_2', django_ckeditor_5.fields.CKEditor5Field()),
                ('head_message_1_paragraph_3', django_ckeditor_5.fields.CKEditor5Field()),
                ('head_message_1_paragraph_4', django_ckeditor_5.fields.CKEditor5Field()),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='about_videos/')),
                ('vision_head_message', django_ckeditor_5.fields.CKEditor5Field()),
                ('vision_message_paragraph_1', django_ckeditor_5.fields.CKEditor5Field()),
                ('vision_message_message_1', django_ckeditor_5.fields.CKEditor5Field()),
                ('vision_message_message_2', django_ckeditor_5.fields.CKEditor5Field()),
                ('vision_message_message_3', django_ckeditor_5.fields.CKEditor5Field()),
                ('vision_message_message_4', django_ckeditor_5.fields.CKEditor5Field()),
                ('vision_message_message_5', django_ckeditor_5.fields.CKEditor5Field()),
                ('vision_message_message_6', django_ckeditor_5.fields.CKEditor5Field()),
                ('vision_message_paragraph_2', django_ckeditor_5.fields.CKEditor5Field()),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='about_images/')),
            ],
        ),
    ]
