# Generated by Django 5.1.7 on 2025-03-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='head_message_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='head_message_1_message_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='head_message_1_message_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='head_message_1_message_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='head_message_1_message_4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='head_message_1_paragraph_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='head_message_1_paragraph_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='head_message_1_paragraph_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='head_message_1_paragraph_4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_head_message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_message_message_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_message_message_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_message_message_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_message_message_4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_message_message_5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_message_message_6',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_message_paragraph_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_message_paragraph_2',
            field=models.TextField(),
        ),
    ]
